# Generated by Django 2.0.6 on 2018-06-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=20)),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_year', models.CharField(max_length=10)),
            ],
        ),
    ]
